version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"  #wasashlelia productionistvis
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"   #wasashlelia productionistvis

  sheukvete-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jomarja/sheukvete-app:latest
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/main
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      DB_HOST: postgres
      DB_PORT: "5432"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: "6379"
      SERVER_PORT: "8081"
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -Xms512m -Xmx1024m"
    ports:
      - "8081:8081"
#      - "8082:8082"   #wasashlelia productionistvis
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/admin/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
